description: resnet18/resnet18-base-dropout-wd-balanced + random vertical/horizontal flip + subtract mean + cutout + efficientnet-b4

model:
    name: classification
    batch_size: 32
    epochs: 1000
    optimizer:
      name: SGD
      args:
        lr: 0.01
        weight_decay: 0.1
      scheduler:
        update: epoch
        value: auc-roc
        name: ReduceLROnPlateau
        params:
            mode: 'max'
            factor: 0.1
            patience: 5
            verbose: true
            threshold: 0.0001
            min_lr: 0.00001
            threshold_mode: abs
    loss:
      train:
        name: binary-cross-entropy
        params:
            reduction: none
      val:
        name: binary-cross-entropy
        params:
            reduction: none
    classes:
      - 0
      - 1
    eval:
      maximize_metric: precision
      maximize_mode: val
    save:
      period: 100
      monitor: auc-roc
      monitor_mode: max
    load:
      version: null
      epoch: -1
      load_best: False
      resume_optimizer: False

network:
    name: neural_net
    params:
        config:
        - name: efficientnet-b4
          params:
            in_channels: 3
            num_classes: 1

data:
  data_type: image
  signal_transform:
    train:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: SubtractMean
      params:
        mean:
          - 104
          - 117
          - 123
        dim: 0
    - name: RandomVerticalFlip
      params:
        p: 0.5
    - name: RandomHorizontalFlip
      params:
        p: 0.5
    - name: RandomErasing
      params:
        p: 0.5

    val:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: SubtractMean
      params:
        mean:
          - 104
          - 117
          - 123
        dim: 0
  dataset:
    name: classification_dataset
    config:
      - name: siim-isic-melanoma
        version: v1.0-200x200
    params:
      train:
        fraction: 1
      val:
        fraction: 1

  sampler:
    train:
        name: classification
        params:
            mode: balanced
    val:
        name: default
    test:
        name: default
  collate_fn:
    name: classification_collate
    params: {}
