description: resnet50/aug-no-balanced + rescale to 0-1 and then mean and std normalize + efficientnet-b4

model:
    name: classification
    batch_size: 64
    epochs: 1000
    optimizer:
      name: SGD
      args:
        lr: 0.1
      scheduler:
        update: epoch
        value: loss
        name: ReduceLROnPlateau
        params:
            mode: 'min'
            factor: 0.1
            patience: 10
            verbose: true
            threshold: 0.0001
            threshold_mode: abs
            min_lr: 0.000001
    loss:
      train:
        name: binary-cross-entropy
        params:
            reduction: none
      val:
        name: binary-cross-entropy
        params:
            reduction: none
      test:
        name: binary-cross-entropy
        params:
            reduction: none
    classes:
      - 0
      - 1
    eval:
      maximize_metric: specificity
      maximize_mode: val
    save:
      period: 100
      monitor: auc-roc
      monitor_mode: max
    load:
      version: null
      epoch: -1
      load_best: False
      resume_optimizer: False

network:
    name: neural_net
    params:
        config:
        - name: efficientnet-b4
          params:
            in_channels: 3
            num_classes: 1

data:
  data_type: image
  signal_transform:
    train:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: RandomVerticalFlip
      params:
        p: 0.5
    - name: RandomHorizontalFlip
      params:
        p: 0.5
    - name: Rescale
      params:
        value: 255.
    - name: Normalize
      params:
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225

    val:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: Rescale
      params:
        value: 255.
    - name: Normalize
      params:
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225

    test:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: Rescale
      params:
        value: 255.
    - name: Normalize
      params:
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
  dataset:
    name: classification_dataset
    config:
      - name: siim-isic-melanoma
        version: v1.0-200x200
    params:
      train:
        fraction: 1
      val:
        fraction: 1
  collate_fn:
    name: classification_collate
    params: {}
