description: looking to replicate this kernel (with resnet50) - https://www.kaggle.com/cdeotte/triple-stratified-kfold-with-tfrecords

model:
    name: classification
    batch_size: 48
    epochs: 12
    optimizer:
      name: Adam
      args:
        lr: 0.001
      scheduler:
        name: 1cycle
        update: batch
        params:
            max_lr: 0.00006
            epochs: 12
            steps_per_epoch: 813
            pct_start: 0.4
            div_factor: 8
    loss:
      train:
        name: binary-cross-entropy
        params:
            reduction: none
      val:
        name: binary-cross-entropy
        params:
            reduction: none
      test:
        name: binary-cross-entropy
        params:
            reduction: none
    classes:
      - 0
      - 1
    eval:
      maximize_metric: specificity
      maximize_mode: val
    save:
      period: 100
      monitor: auc-roc
      monitor_mode: max
    load:
      version: null
      epoch: -1
      load_best: False
      resume_optimizer: False

network:
    name: neural_net
    params:
        config:
        - name: resnet50
          params:
            in_channels: 3
            pretrained: true
        - name: AdaptiveAvgPool2d
          params:
            output_size:
            - 1
            - 1
        - name: Flatten
          params: {}
        - name: Dropout
          params:
            p: 0.2
        - name: Linear
          params:
            in_features: 2048
            out_features: 1

data:
  data_type: image
  signal_transform:
    train:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: Rescale
      params:
        value: 255.
    - name: RandomAffine
      params:
        degrees: 180
        translate:
          - 0.02
          - 0.02
        scale:
          - 8
          - 8
        shear:
          - 2
          - 0
    - name: RandomHorizontalFlip
      params:
        p: 0.5
    - name: ColorJitter
      params:
        saturation:
          - 0.7
          - 1.3
    - name: ColorJitter
      params:
        contrast:
          - 0.8
          - 1.2
    - name: ColorJitter
      params:
        brightness: 0.1
    

    val:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: Rescale
      params:
        value: 255.
    - name: RandomAffine
      params:
        degrees: 180
        translate:
          - 0.02
          - 0.02
        scale:
          - 8
          - 8
        shear:
          - 2
          - 0
    - name: RandomHorizontalFlip
      params:
        p: 0.5
    - name: ColorJitter
      params:
        saturation:
          - 0.7
          - 1.3
    - name: ColorJitter
      params:
        contrast:
          - 0.8
          - 1.2
    - name: ColorJitter
      params:
        brightness: 0.1

    test:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: Rescale
      params:
        value: 255.
    - name: RandomAffine
      params:
        degrees: 180
        translate:
          - 0.02
          - 0.02
        scale:
          - 8
          - 8
        shear:
          - 2
          - 0
    - name: RandomHorizontalFlip
      params:
        p: 0.5
    - name: ColorJitter
      params:
        saturation:
          - 0.7
          - 1.3
    - name: ColorJitter
      params:
        contrast:
          - 0.8
          - 1.2
    - name: ColorJitter
      params:
        brightness: 0.1

  dataset:
    name: classification_dataset
    config:
      - name: siim-isic-melanoma
        version: v3.0.0
    params:
      train:
        fraction: 1
      val:
        fraction: 1
  collate_fn:
    name: classification_collate
    params: {}
