description: looking to replicate kaggle kernel + using CIFAR-10 baseline
entity: dalmiaman
project: melanoma-classification

model:
    name: classification
    batch_size: 512
    epochs: 35
    optimizer:
      name: Adam
      args:
        lr: 0.000005
      scheduler:
        name: 1cycle
        update: batch
        params:
            max_lr: 0.00064
            epochs: 35
            steps_per_epoch: 153
            pct_start: 0.4
            div_factor: 128
    loss:
      train:
        name: binary-cross-entropy
        params:
            reduction: none
      val:
        name: binary-cross-entropy
        params:
            reduction: none

      test:
        name: binary-cross-entropy
        params:
            reduction: none
    classes:
      - 0
      - 1
    eval:
      maximize_metric: specificity
    save:
      period: 2
      monitor: auc-roc
      monitor_mode: max
    load:
      version: null
      epoch: -1
      load_best: False
      resume_optimizer: False

network:
    name: neural_net
    params:
        config:
        - name: resnet18
          params:
            in_channels: 3
            pretrained: true
        - name: AdaptiveAvgPool2d
          params:
            output_size:
            - 1
            - 1
        - name: Flatten
          params: {}
        - name: Linear
          params:
            in_features: 512
            out_features: 1

data:
  data_type: image
  signal_transform:
    train:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: Rescale
      params:
        value: 255.
    - name: RandomHorizontalFlip
      params:
        p: 0.5
    - name: RandomCrop
      params:
        size:
          - 224
          - 224
    - name: Normalize
      params:
        mean: imagenet
        std: imagenet

    val:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: Rescale
      params:
        value: 255.
    - name: RandomHorizontalFlip
      params:
        p: 0.5
    - name: RandomCrop
      params:
        size:
          - 224
          - 224
    - name: Normalize
      params:
        mean: imagenet
        std: imagenet

    test:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: Rescale
      params:
        value: 255.
    - name: RandomHorizontalFlip
      params:
        p: 0.5
    - name: RandomCrop
      params:
        size:
          - 224
          - 224
    - name: Normalize
      params:
        mean: imagenet
        std: imagenet

  dataset:
    name: classification_dataset
    config:
      - name: siim-isic-melanoma
        version: v3.0.3
    params: {}
  collate_fn:
    name: classification_collate
    params: {}
