description: looking to replicate kaggle kernel + using CIFAR-10 baseline + rotation + jitter
entity: dalmiaman
project: melanoma-classification

model:
    name: classification
    batch_size: 128
    epochs: 35
    optimizer:
      name: AdamW
      args:
        lr: 0.00012
        weight_decay: 0.4
      scheduler:
        name: 1cycle
        update: batch
        params:
            max_lr: 0.003
            epochs: 35
            steps_per_epoch: 153
            pct_start: 0.3
            div_factor: 25
    loss:
      train:
        name: binary-cross-entropy
        params:
            reduction: none
      val:
        name: binary-cross-entropy
        params:
            reduction: none
    classes:
      - 0
      - 1
    eval:
      maximize_metric: specificity
    save:
      period: 2
      monitor: auc-roc
      monitor_mode: max
    load:
      version: null
      epoch: -1
      load_best: False
      resume_optimizer: False

network:
    name: neural_net
    params:
        config:
        - name: resnet18
          params:
            in_channels: 3
            pretrained: true
        - name: AdaptiveAvgPool2d
          params:
            output_size:
            - 1
            - 1
        - name: Flatten
          params: {}
        - name: Linear
          params:
            in_features: 512
            out_features: 1

data:
  data_type: image
  signal_transform:
    train:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: Rescale
      params:
        value: 255.
    - name: RandomAffine
      params:
        degrees: 180
        translate:
          - 0.02
          - 0.02
        shear:
          - 2
          - 0
    - name: RandomHorizontalFlip
      params:
        p: 0.5
    - name: RandomCrop
      params:
        size:
          - 224
          - 224
    - name: ColorJitter
      params:
        saturation:
          - 0.7
          - 1.3
    - name: ColorJitter
      params:
        contrast:
          - 0.8
          - 1.2
    - name: ColorJitter
      params:
        brightness: 0.1
    - name: Normalize
      params:
        mean: imagenet
        std: imagenet

    val:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: Rescale
      params:
        value: 255.
    - name: RandomAffine
      params:
        degrees: 180
        translate:
          - 0.02
          - 0.02
        shear:
          - 2
          - 0
    - name: RandomHorizontalFlip
      params:
        p: 0.5
    - name: RandomCrop
      params:
        size:
          - 224
          - 224
    - name: ColorJitter
      params:
        saturation:
          - 0.7
          - 1.3
    - name: ColorJitter
      params:
        contrast:
          - 0.8
          - 1.2
    - name: ColorJitter
      params:
        brightness: 0.1
    - name: Normalize
      params:
        mean: imagenet
        std: imagenet

  dataset:
    name: classification_dataset
    config:
      - name: siim-isic-melanoma
        version: v3.0.0
    params: {}
  collate_fn:
    name: classification_collate
    params: {}
