description: resnet18-base + fraction 0.1 + LR=1e-2 + SGD

model:
    name: classification
    batch_size: 32
    epochs: 1000
    optimizer:
      name: SGD
      args:
        lr: 0.01
    loss:
      train:
        name: binary-cross-entropy
        params:
            reduction: none
      val:
        name: binary-cross-entropy
        params:
            reduction: none
      test:
        name: binary-cross-entropy
        params:
            reduction: none
    classes:
      - 0
      - 1
    eval:
      maximize_metric: precision
      maximize_mode: val
    save:
      period: 2
      monitor: precision
      monitor_mode: max
    load:
      version: null
      epoch: -1
      load_best: False
      resume_optimizer: False

network:
    name: neural_net
    params:
        config:
        - name: resnet18
          params:
            in_channels: 3
            pretrained: true
        - name: AdaptiveAvgPool2d
          params:
            output_size:
            - 1
            - 1
        - name: Flatten
          params: {}
        - name: Linear
          params:
            in_features: 512
            out_features: 1

data:
  data_type: image
  signal_transform:
    train:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    val:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    test:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
  dataset:
    name: classification_dataset
    config:
      - name: siim-isic-melanoma
        version: v1.0-200x200
    params:
      train:
        fraction: 0.1
      val:
        fraction: 0.1
  collate_fn:
    name: classification_collate
    params: {}
