description: normalized-wd-dropout + momentum + cyclicLR

model:
    name: classification
    batch_size: 128
    epochs: 100
    optimizer:
      name: SGD
      args:
        lr: 0.01
        momentum: 0.9
        nesterov: true
        weight_decay: 0.001
      scheduler:
        name: CyclicLR
        update: batch
        params:
            base_lr: 0.00001
            max_lr: 0.01
            step_size_up: 207
            gamma: 0.99994
            mode: exp_range
            cycle_momentum: true
    loss:
      train:
        name: binary-cross-entropy
        params:
            reduction: none
      val:
        name: binary-cross-entropy
        params:
            reduction: none
    classes:
      - 0
      - 1
    eval:
      maximize_metric: specificity
      maximize_mode: val
    save:
      period: 100
      monitor: auc-roc
      monitor_mode: max
    load:
      version: null
      epoch: -1
      load_best: False
      resume_optimizer: False

network:
    name: neural_net
    params:
        config:
        - name: resnet50
          params:
            in_channels: 3
            pretrained: true
        - name: AdaptiveAvgPool2d
          params:
            output_size:
            - 1
            - 1
        - name: Flatten
          params: {}
        - name: Dropout
          params:
            p: 0.2
        - name: Linear
          params:
            in_features: 2048
            out_features: 1

data:
  data_type: image
  signal_transform:
    train:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: RandomVerticalFlip
      params:
        p: 0.5
    - name: RandomHorizontalFlip
      params:
        p: 0.5
    - name: Rescale
      params:
        value: 255.
    - name: Normalize
      params:
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225

    val:
    - name: Permute
      params:
        order:
          - 2
          - 0
          - 1
    - name: Rescale
      params:
        value: 255.
    - name: Normalize
      params:
        mean:
          - 0.485
          - 0.456
          - 0.406
        std:
          - 0.229
          - 0.224
          - 0.225
  dataset:
    name: classification_dataset
    config:
      - name: siim-isic-melanoma
        version: v1.0-200x200
    params:
      train:
        fraction: 1
      val:
        fraction: 1
  collate_fn:
    name: classification_collate
    params: {}
